-- MySQL Script generated by MySQL Workbench
-- Sun Sep  6 12:51:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`community` (
  `idcommunity` INT NOT NULL,
  `comunityname` VARCHAR(45) NOT NULL,
  `ownerid` INT NOT NULL,
  PRIMARY KEY (`idcommunity`),
  INDEX `fk_community_user1_idx` (`ownerid` ASC) VISIBLE,
  CONSTRAINT `fk_community_user1`
    FOREIGN KEY (`ownerid`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `communityid` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_community_idx` (`communityid` ASC) VISIBLE,
  CONSTRAINT `fk_user_community`
    FOREIGN KEY (`communityid`)
    REFERENCES `mydb`.`community` (`idcommunity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`foodallocate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`foodallocate` (
  `idfoodallocate` INT NOT NULL,
  `community_idcommunity` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idfoodallocate`),
  INDEX `fk_foodallocate_community1_idx` (`community_idcommunity` ASC) VISIBLE,
  INDEX `fk_foodallocate_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_foodallocate_community1`
    FOREIGN KEY (`community_idcommunity`)
    REFERENCES `mydb`.`community` (`idcommunity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_foodallocate_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`announcement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`announcement` (
  `idannouncement` INT NOT NULL,
  `community_idcommunity` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `content` LONGTEXT NULL,
  `text` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idannouncement`),
  INDEX `fk_announcement_community1_idx` (`community_idcommunity` ASC) VISIBLE,
  INDEX `fk_announcement_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_announcement_community1`
    FOREIGN KEY (`community_idcommunity`)
    REFERENCES `mydb`.`community` (`idcommunity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_announcement_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`complaint` (
  `idcomplaint` INT NOT NULL,
  `community_idcommunity` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`idcomplaint`),
  INDEX `fk_complaint_community1_idx` (`community_idcommunity` ASC) VISIBLE,
  INDEX `fk_complaint_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_complaint_community1`
    FOREIGN KEY (`community_idcommunity`)
    REFERENCES `mydb`.`community` (`idcommunity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complaint_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
